/*
 * File: app/model/MyModel.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Customers.model.MyModel', {
    extend: 'Ext.data.Model',
    alias: 'model.mymodel',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    clientIdProperty: 'CUST_NO',
    idProperty: 'CUST_NO',

    fields: [
        {
            type: 'int',
            name: 'CUST_NO'
        },
        {
            type: 'string',
            name: 'CUSTOMER'
        },
        {
            type: 'string',
            name: 'CONTACT_FIRST'
        },
        {
            type: 'string',
            name: 'CONTACT_LAST'
        },
        {
            type: 'string',
            name: 'PHONE_NO'
        },
        {
            type: 'string',
            name: 'ADDRESS_LINE1'
        },
        {
            name: 'ADDRESS_LINE2'
        },
        {
            type: 'string',
            name: 'CITY'
        },
        {
            type: 'string',
            name: 'STATE_PROVINCE'
        },
        {
            type: 'string',
            name: 'COUNTRY'
        },
        {
            type: 'string',
            name: 'POSTAL_CODE'
        },
        {
            name: 'ON_HOLD'
        }
    ]
});