/*
 * File: app/view/CustomersModel.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Customers.view.CustomersModel', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.customersmodel',

    requires: [
        'Customers.view.CustomersModelViewModel',
        'Customers.view.CustomersModelViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.form.field.Display',
        'Ext.form.Panel',
        'Ext.form.field.Number',
        'Ext.button.Button',
        'Ext.toolbar.Toolbar'
    ],

    controller: 'customersmodel',
    viewModel: {
        type: 'customersmodel'
    },
    height: 250,
    width: 400,
    layout: 'fit',

    items: [
        {
            xtype: 'panel',
            shrinkWrap: 0,
            layout: 'border',
            collapsed: false,
            title: 'Customers',
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    region: 'center',
                    split: true,
                    reference: 'list',
                    resizable: false,
                    title: '',
                    forceFit: true,
                    bind: {
                        store: '{myModels}'
                    },
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'CUST_NO',
                            text: 'Cust No',
                            format: '00'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'CUSTOMER',
                            text: 'Customer'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'CONTACT_FIRST',
                            text: 'Contact First'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'CONTACT_LAST',
                            text: 'Contact Last'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'PHONE_NO',
                            text: 'Phone No'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ADDRESS_LINE1',
                            text: 'Address Line1'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ADDRESS_LINE2',
                            text: 'Address Line2'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'CITY',
                            text: 'City'
                        }
                    ],
                    listeners: {
                        select: 'select'
                    }
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'east',
                    split: true,
                    reference: 'display',
                    width: 150,
                    layout: 'card',
                    bodyBorder: true,
                    items: [
                        {
                            xtype: 'panel',
                            reference: 'selectMessage',
                            layout: {
                                type: 'vbox',
                                align: 'center',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    html: '"<h1>Please select a record</h1>"'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            reference: 'details',
                            bodyPadding: 10,
                            items: [
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Cust No',
                                    bind: {
                                        value: '{record.CUST_NO}'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Customer',
                                    bind: {
                                        value: '{record.CUSTOMER}'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Contact First',
                                    bind: {
                                        value: '{record.CONTACT_FIRST}'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Contact Last',
                                    bind: {
                                        value: '{record.CONTACT_LAST}'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Phone No',
                                    bind: {
                                        value: '{record.PHONE_NO}'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Address Line1',
                                    bind: {
                                        value: '{record.ADDRESS_LINE1}'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Address Line2',
                                    bind: {
                                        value: '{record.ADDRESS_LINE2}'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'City',
                                    bind: {
                                        value: '{record.CITY}'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'State Province',
                                    bind: {
                                        value: '{record.STATE_PROVINCE}'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Country',
                                    bind: {
                                        value: '{record.COUNTRY}'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Postal Code',
                                    bind: {
                                        value: '{record.POSTAL_CODE}'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'On Hold',
                                    bind: {
                                        value: '{record.ON_HOLD}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            reference: 'form',
                            bodyPadding: 10,
                            title: 'Edit MyModel',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    width: 180,
                                    fieldLabel: 'Cust No',
                                    name: 'CUST_NO'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Customer',
                                    name: 'CUSTOMER'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Contact First',
                                    name: 'CONTACT_FIRST'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Contact Last',
                                    name: 'CONTACT_LAST'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Phone No',
                                    name: 'PHONE_NO',
                                    emptyText: 'xxx-xxx-xxxx',
                                    regex: /^\d{3}-\d{3}-\d{4}$/,
                                    regexText: 'Please enter a valid phone number xxx-xxx-xxxx'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 400,
                                    fieldLabel: 'Address Line1',
                                    name: 'ADDRESS_LINE1'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Address Line2',
                                    name: 'ADDRESS_LINE2'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'City',
                                    name: 'CITY'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'State Province',
                                    name: 'STATE_PROVINCE'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Country',
                                    name: 'COUNTRY'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Postal Code',
                                    name: 'POSTAL_CODE'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'On Hold',
                                    name: 'ON_HOLD'
                                },
                                {
                                    xtype: 'container',
                                    padding: 10,
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            formBind: true,
                                            itemId: 'saveButton',
                                            margin: 5,
                                            text: 'Save',
                                            listeners: {
                                                click: 'save'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            itemId: 'cancelButton',
                                            margin: 5,
                                            text: 'Cancel',
                                            listeners: {
                                                click: 'cancelEdit'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Add',
                            listeners: {
                                click: 'add'
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Edit',
                            bind: {
                                hidden: '{!record}'
                            },
                            listeners: {
                                click: 'edit'
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Remove',
                            bind: {
                                hidden: '{!record}'
                            },
                            listeners: {
                                click: 'remove'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});